version: "3.8"

services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/conf.d:/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  acme-companion:
    restart: always
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
      - ./volumes/acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=mail@hartmark.se

  root-website:
    restart: always
    build: ./services/website
    container_name: root-website
    volumes:
      - "./volumes/root-website/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=staropramen.harre.dynv6.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=staropramen.harre.dynv6.net
      - LETSENCRYPT_EMAIL=mail@hartmark.se
    extra_hosts:
      - host.docker2.internal:192.168.1.50
